# Generated by Django 4.2.10 on 2024-02-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on']},
        ),
    ]
